#!/bin/bash

#$ -o /exports/eddie/scratch/ebarbier/logfiles
#$ -e /exports/eddie/scratch/ebarbier/logfiles
#$ -pe sharedmem 4
#$ -l h_vmem=8G
#$ -l h_rt=24:00:00 
#$ -R y 

#CALLING THE VARIABLES
echo $1 # Read project folder same
echo $2 # name of the samples
echo $3 # name of input bam file

#load modules
. /etc/profile.d/modules.sh
module load java/jdk-22.0.1
module load roslin/trim_galore/0.6.10 
module load igmm/apps/cutadapt/4.6
module load roslin/bwa/0.7.18
module load igmm/libs/ncurses/6.0
module load igmm/libs/htslib/1.6
module load igmm/apps/samtools/1.6 
module load anaconda/2024.02
module load igmm/apps/BEDTools/2.27.1
module load roslin/fastqc/0.12.1
module load igmm/apps/bowtie/2.5.3 
module load igmm/apps/OpenJDK/17.0.11
module load igmm/apps/picard/3.1.1
module load igmm/apps/MACS2/2.2.9.1

#creates folders
cd /exports/eddie/scratch/ebarbier/$1

mv $2_R1.fastq.gz 1_fastq/
mv $2_R2.fastq.gz 1_fastq/

cd /exports/eddie/scratch/ebarbier/$1/1_fastq/

gunzip $2_R1.fastq.gz
gunzip $2_R2.fastq.gz

#PERFORMING QC OF THE SEQUENCES WITH FASTQC
fastqc $2_R1.fastq -o /exports/eddie/scratch/ebarbier/$1/2_fastqc_outputs/
fastqc $2_R2.fastq -o /exports/eddie/scratch/ebarbier/$1/2_fastqc_outputs/

#TRIMMING ADAPTERS from reads
##length might be increased based on the length of reads
trim_galore --path_to_cutadapt cutadapt --paired -stringency 5 -length 30 -o /exports/eddie/scratch/ebarbier/$1/3_trimmed_fastq/ -q 20 $2_R1.fastq $2_R2.fastq

cd /exports/eddie/scratch/ebarbier/$1/3_trimmed_fastq/

#gunzip $2_R1_val_1.fq.gz
#gunzip $2_R2_val_2.fq.gz

fastqc $2_R1_val_1.fq -o /exports/eddie/scratch/ebarbier/$1/2_fastqc_outputs/
fastqc $2_R2_val_2.fq -o /exports/eddie/scratch/ebarbier/$1/2_fastqc_outputs/


#BWA MEM ALIGNMENT
bwa mem -t 6 /exports/csce/eddie/biology/groups/chambers/mm10/mm10_bwa_genome/mm10bwaidx $2_R1_val_1.fq $2_R2_val_2.fq | samtools view -Sb - > /exports/eddie/scratch/ebarbier/$1/4_aln/$2_mem.bam

cd /exports/eddie/scratch/ebarbier/$1/4_aln/

#SORT BAM by coordinates
samtools sort -@ 8 -T $2_mem.bam -O bam -o $2_mem_srt.bam $2_mem.bam

#INDEX BAM
samtools index $2_mem_srt.bam

#APPLY Q10 FILTER STEP  and RMDUP
samtools view -@ 8 -q 10 -b $2_mem_srt.bam > $2_mem_srt_q10.bam
java -jar $PICARD MarkDuplicates --REMOVE_DUPLICATES true --ASSUME_SORTED true -I $2_mem_srt_q10.bam -O $2_mem_srt_q10_rmDup.bam -M $2_mem_srt_q10_rmDup_metrics.txt
samtools index $2_mem_srt_q10_rmDup.bam

#THE FOLLOWING COMMANDS RUN THE MAIN STATS FOR THE ALN SEQUENCES
samtools flagstat $2_mem_srt.bam > $2_mem_srt_stats.txt
samtools flagstat $2_mem_srt_q10.bam> $2_mem_srt_q10_stats.txt
samtools flagstat $2_mem_srt_q10_rmDup.bam> $2_mem_srt_q10_rmDup_stats.txt


#PEAK CALLING WITH MACS2
cd /exports/eddie/scratch/ebarbier/$1/5_peaks/

macs2 callpeak -t /exports/eddie/scratch/ebarbier/$1/4_aln/$2_mem_srt_q10_rmDup.bam -c $3 -f BAM -g mm -n $2_mem_q10_srt_rmDup_peaks -B -q 0.05
#YOU WILL GET SEVERAL OUTPUTS IN EXEL, BED AND BEDGRAPH FORMATS, SEE HERE FOR A DESCRIPTION: https://github.com/taoliu/MACS/
bedtools intersect -a $2_mem_q10_srt_rmDup_peaks_peaks.narrowPeak -b /exports/csce/eddie/biology/groups/chambers/mm10_blacklist_new_srt_merged.bed -v > $2_mem_srt_q10_rmDup_peaks_peaks_nobl.bed


#PRODUCE BIGWIG
cd /exports/eddie/scratch/ebarbier/$1/4_aln/
samtools index /exports/eddie/scratch/ebarbier/$1/4_aln/$2_mem_srt_q10_rmDup.bam
conda activate python
bamCoverage --bam /exports/eddie/scratch/ebarbier/$1/4_aln/$2_mem_srt_q10_rmDup.bam --binSize 10 --normalizeUsing RPGC --effectiveGenomeSize 2652783500 --ignoreForNormalization chrX --blackListFileName /exports/csce/eddie/biology/groups/chambers//mm10_blacklist_new_srt_merged.bed -o /exports/eddie/scratch/ebarbier/$1/5_peaks/$2_mem_srt_q10_rmDup_normalized.bw 
##--exactScaling can be used to normalize to a specific number of reads/sample, to make all samples more comparable
conda deactivate

#rm /exports/eddie/scratch/ebarbier/$1/4_aln/$2_mem.bam
rm /exports/eddie/scratch/ebarbier/$1/4_aln/$2_mem_srt.bam
rm /exports/eddie/scratch/ebarbier/$1/4_aln/$2_mem_srt_q10.bam
rm /exports/eddie/scratch/ebarbier/$1/4_aln/$2_mem_srt_q10_rmDup_metrics.txt
rm /exports/eddie/scratch/ebarbier/$1/4_aln/*.bdg
gzip /exports/eddie/scratch/ebarbier/$1/1_fastq/$2_R1.fastq
gzip /exports/eddie/scratch/ebarbier/$1/1_fastq/$2_R2.fastq
gzip /exports/eddie/scratch/ebarbier/$1/3_trimmed_fastq/$2_R1_val_1.fq
gzip /exports/eddie/scratch/ebarbier/$1/3_trimmed_fastq/$2_R2_val_2.fq

