#!/bin/bash

#$ -o /exports/eddie/scratch/ebarbier/logfiles
#$ -e /exports/eddie/scratch/ebarbier/logfiles
#$ -pe sharedmem 4
#$ -l h_vmem=8G

#CALLING THE VARIABLES
echo $1 # Read project folder same as samples' names
echo $2 # name of the samples

#load modules
. /etc/profile.d/modules.sh
module load java/jdk-22.0.1
module load roslin/trim_galore/0.6.10 
module load igmm/apps/cutadapt/4.6
module load roslin/bwa/0.7.18
module load igmm/libs/ncurses/6.0
module load igmm/libs/htslib/1.6
module load igmm/apps/samtools/1.6 
module load anaconda/2024.02
module load igmm/apps/BEDTools/2.27.1
module load roslin/fastqc/0.12.1
module load igmm/apps/bowtie/2.5.3 
module load igmm/apps/OpenJDK/17.0.11
module load igmm/apps/picard/3.1.1
module load igmm/apps/MACS2/2.2.9.1 


#creates folders
cd /exports/eddie/scratch/ebarbier/$1
mkdir 1_fastq
mkdir 4_aln
mkdir 2_fastqc_outputs
mkdir 5_peaks
mkdir 3_trimmed_fastq

mv $2.fastq.gz 1_fastq/
mv $2.fastq 1_fastq/

cd /exports/eddie/scratch/ebarbier/$1/1_fastq/

gunzip $2.fastq.gz

#PERFORMING QC OF THE SEQUENCES WITH FASTQC
fastqc $2.fastq -o /exports/eddie/scratch/ebarbier/$1/2_fastqc_outputs/

#TRIMMING ADAPTERS from reads
trim_galore --path_to_cutadapt cutadapt -stringency 5 -length 35 -o /exports/eddie/scratch/ebarbier/$1/3_trimmed_fastq/ -q 20 $2.fastq 

cd /exports/eddie/scratch/ebarbier/$1/3_trimmed_fastq/

gunzip $2_trimmed.fq.gz

#BWA MEM ALIGNMENT
bwa mem -t 6 /exports/csce/eddie/biology/groups/chambers/mm10/mm10_bwa_genome/mm10bwaidx $2_trimmed.fq | samtools view -Sb - > /exports/eddie/scratch/ebarbier/$1/4_aln/$2_mem.bam

cd /exports/eddie/scratch/ebarbier/$1/4_aln/

# SORT ALIGNMENT
samtools sort -@ 8 -T $2_mem.bam -O bam -o $2_mem_srt.bam $2_mem.bam
samtools index $2_mem_srt.bam

#APPLY Q10 FILTER STEP  and RMDUP
samtools view -@ 8 -q 10 -b $2_mem_srt.bam > $2_mem_srt_q10.bam
java -jar $PICARD MarkDuplicates --REMOVE_DUPLICATES true --ASSUME_SORTED true -I $2_mem_srt_q10.bam -O $2_mem_srt_q10_rmDup.bam -M $2_mem_srt_q10_mkDup_metrics.txt
samtools index $2_mem_srt_q10_rmDup.bam

#THE FOLLOWING COMMANDS RUN THE MAIN STATS FOR THE ALN SEQUENCES 
samtools flagstat $2_mem.bam > $2_mem.txt
samtools flagstat $2_mem_srt_q10_rmDup.bam > $2_mem_srt_q10_rmDup.txt

#PRODUCE BIGWIG
conda activate python
bamCoverage --bam /exports/eddie/scratch/ebarbier/$1/4_aln/$2_mem_srt_q10_rmDup.bam --binSize 10 --normalizeUsing RPGC --effectiveGenomeSize 2652783500 --ignoreForNormalization chrX --blackListFileName ~/mm10_blacklist_new_srt_merged.bed -o /exports/eddie/scratch/ebarbier/$1/5_peaks/$2_mem_srt_q10_rmDup_normalized.bw
conda deactivate



rm /exports/eddie/scratch/ebarbier/$1/4_aln/$2_mem.bam
gzip /exports/eddie/scratch/ebarbier/$1/1_fastq/$2.fastq
gzip /exports/eddie/scratch/ebarbier/$1/3_trimmed_fastq/$2_trimmed.fq
